// Typelizer digest 7632bb7f3e78c1f4f4722a3447cda4b7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /rails/mailers */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/rails/mailers', {}, options),
    method: 'get',
  }),
}
