// Typelizer digest 45a8d8529ed8fbe0e1bd74e975c79376
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../../../runtime'
import { buildUrl } from '../../../runtime'

export default {
  /** GET /rails/conductor/action_mailbox/inbound_emails */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/inbound_emails', {}, options),
    method: 'get',
  }),

  /** POST /rails/conductor/action_mailbox/inbound_emails */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/inbound_emails', {}, options),
    method: 'post',
  }),

  /** GET /rails/conductor/action_mailbox/inbound_emails/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/inbound_emails/new', {}, options),
    method: 'get',
  }),

  /** GET /rails/conductor/action_mailbox/inbound_emails/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/inbound_emails/:id', params, options),
    method: 'get',
  }),
}
