// Typelizer digest 5217911ef9a8e4b55d5779b7c56c3d9c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../../../runtime'
import { buildUrl } from '../../../runtime'

export default {
  /** POST /rails/conductor/action_mailbox/:inbound_email_id/incinerate */
  create: (
    params: { inboundEmailId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/:inbound_email_id/incinerate', params, options),
    method: 'post',
  }),
}
