// Typelizer digest 14fa72ea5c016c0e2378f3f17cb68039
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../../../runtime'
import { buildUrl } from '../../../runtime'

export default {
  /** POST /rails/conductor/action_mailbox/:inbound_email_id/reroute */
  create: (
    params: { inboundEmailId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/:inbound_email_id/reroute', params, options),
    method: 'post',
  }),
}
