// Typelizer digest 3d95bc0d09146f402e93a9de9451c8c5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../../../runtime'
import { buildUrl } from '../../../runtime'

export default {
  /** POST /rails/action_mailbox/postmark/inbound_emails */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/rails/action_mailbox/postmark/inbound_emails', {}, options),
    method: 'post',
  }),
}
