// Typelizer digest d7684df287c4dc147bb37458b1037fc1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from "../../../runtime";
import { buildUrl } from "../../../runtime";

export default {
  /** POST /rails/action_mailbox/mailgun/inbound_emails/mime */
  create: (options?: RouteOptions): RouteDefinition<"post"> => ({
    url: buildUrl(
      "/rails/action_mailbox/mailgun/inbound_emails/mime",
      {},
      options,
    ),
    method: "post",
  }),
};
