// Typelizer digest 8deb18d3eab5e7720e1a9a6a08c6b1b9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../../../runtime'
import { buildUrl } from '../../../runtime'

export default {
  /** GET /rails/action_mailbox/mandrill/inbound_emails */
  healthCheck: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/rails/action_mailbox/mandrill/inbound_emails', {}, options),
    method: 'get',
  }),

  /** POST /rails/action_mailbox/mandrill/inbound_emails */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/rails/action_mailbox/mandrill/inbound_emails', {}, options),
    method: 'post',
  }),
}
