default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: transcripthub_development
  host: localhost
  username: eduardsalagranferragut
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
