// Typelizer digest 641d054a32dd90fee4b323b4c6776b44
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from "./runtime";
import { buildUrl } from "./runtime";

export default {
  /** GET /files */
  index: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/files", {}, options),
    method: "get",
  }),

  /** POST /files */
  create: (options?: RouteOptions): RouteDefinition<"post"> => ({
    url: buildUrl("/files", {}, options),
    method: "post",
  }),

  /** PATCH /files/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"patch"> => ({
    url: buildUrl("/files/:id", params, options),
    method: "patch",
  }),

  /** DELETE /files/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"delete"> => ({
    url: buildUrl("/files/:id", params, options),
    method: "delete",
  }),
};
