// Typelizer digest 73131df811a1f741df0435617d259390
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET / */
  root: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/', {}, options),
    method: 'get',
  }),

  /** GET /home/index */
  homeIndex: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/home/index', {}, options),
    method: 'get',
  }),
}
