// Typelizer digest 73d7b36ca423d5d95bb71dc1d56c0ffc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from "./runtime";
import { buildUrl } from "./runtime";

export default {
  /** GET /inertia-example */
  index: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/inertia-example", {}, options),
    method: "get",
  }),
};
