// Typelizer digest f6342f86c5f1fdfcae3097bc33c5f282
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from "./runtime";
import { buildUrl } from "./runtime";

export default {
  /** GET /signup */
  new: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/signup", {}, options),
    method: "get",
  }),

  /** POST /signup */
  create: (options?: RouteOptions): RouteDefinition<"post"> => ({
    url: buildUrl("/signup", {}, options),
    method: "post",
  }),
};
