// Typelizer digest 14b979ef60c22f48dddcfa6c2386467d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /login */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/login', {}, options),
    method: 'get',
  }),

  /** POST /login */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/login', {}, options),
    method: 'post',
  }),

  /** DELETE /logout */
  destroy: (options?: RouteOptions): RouteDefinition<'delete'> => ({
    url: buildUrl('/logout', {}, options),
    method: 'delete',
  }),
}
