// Typelizer digest bca45bd6eb0fd45040f51b0fb4679472
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../../../../runtime'
import { buildUrl } from '../../../../runtime'

export default {
  /** GET /rails/conductor/action_mailbox/inbound_emails/sources/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/inbound_emails/sources/new', {}, options),
    method: 'get',
  }),

  /** POST /rails/conductor/action_mailbox/inbound_emails/sources */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/rails/conductor/action_mailbox/inbound_emails/sources', {}, options),
    method: 'post',
  }),
}
