// Typelizer digest 659c7eae61e76727699584fcc22c477a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from "../../../runtime";
import { buildUrl } from "../../../runtime";

export default {
  /** POST /rails/action_mailbox/relay/inbound_emails */
  create: (options?: RouteOptions): RouteDefinition<"post"> => ({
    url: buildUrl("/rails/action_mailbox/relay/inbound_emails", {}, options),
    method: "post",
  }),
};
