// Typelizer digest 83f3a880c65e1a6c1c40963449a9448c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from "../../../runtime";
import { buildUrl } from "../../../runtime";

export default {
  /** POST /rails/action_mailbox/sendgrid/inbound_emails */
  create: (options?: RouteOptions): RouteDefinition<"post"> => ({
    url: buildUrl("/rails/action_mailbox/sendgrid/inbound_emails", {}, options),
    method: "post",
  }),
};
