// Typelizer digest 50f773ac77965ab7f651e38dce320d91
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type StoredFileStatus =
  | "uploading"
  | "processing"
  | "available"
  | "quarantined"
  | "failed"
  | "archived"
  | "deleted";
