// Typelizer digest 6ee801b85833e0bb7cf7cc7c1b4a96e6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { StoredFileStatus } from "@/types";

type StoredFile = {
  id: number;
  name: string | null;
  description: string | null;
  file_hash: string | null;
  created_at: string;
  updated_at: string;
  status: StoredFileStatus;
};

export default StoredFile;
